name: Build Status

on:
  push:
    branches:
      - master
      - next-*
      - fix-v*
    tags:
      - v**
  pull_request:
    branches:
      - master
      - next-*
      - fix-v*

jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Check format
        run: yarn format:check
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}-${{matrix.node-version}}
      - name: Using Node v${{matrix.node-version}}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Unit tests
        run: yarn test
  production_package:
    name: "Build production package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}-v14.x
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build production package
        run: yarn build
      - name: Create bundle
        run: |
          yarn pack
          mv ava-fast-check-*.tgz ava-fast-check.tgz
      - name: Upload production package
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: ava-fast-check.tgz
          if-no-files-found: error
          retention-days: 1
  test_cjs:
    name: "Test CommonJS"
    needs: production_package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
      - name: Download production package
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Untar the published package
        run: |
          mkdir bundle
          tar -zxvf ava-fast-check.tgz -C bundle
      - name: Test
        run: |
          cd test-bundle/commonjs
          yarn
          yarn test
  test_esm:
    name: "Test ESM"
    needs: production_package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
      - name: Download production package
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Untar the published package
        run: |
          mkdir bundle
          tar -zxvf ava-fast-check.tgz -C bundle
      - name: Test
        run: |
          cd test-bundle/esm
          yarn
          yarn test
  publish_package:
    name: "Publish package"
    needs:
      - production_package
      - format
      - test
      - test_cjs
      - test_esm
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Download production package
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Publish package
        run: npm publish ava-fast-check.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
